language: node_js
node_js:
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
services:
  - mongodb 

before_script:
  - npm install coffee-script -g
  - npm install  

script:
  - coffee server.coffee

after_failure:
  -
