language: node_js
node_js:
  - "0.10"
services:
  - mongodb 

before_script:
  - npm install coffee-script -g
  - npm install forever -g
  - npm install  
  

script:
  - forever -l ./server.log start -c coffee server.coffee 
  - forever list
#  - npm test
  - wget http://127.0.0.1:1024/api/ping

after_failure:
  - cat ~/.forever/server.log

notifications:
  slack: ngacn:g7UKlznzOydd9RD1fDwYjXLi
