language: node_js
node_js:
  - "0.10"
services:
  - mongodb 

before_script:
  - npm install coffee-script -g
  - npm install  

script:
  - coffee server.coffee &
  - npm test

after_failure:
  -
notifications:
  slack: ngacn:g7UKlznzOydd9RD1fDwYjXLi
