language: node_js
node_js:
  - "0.10"
services:
  - mongodb 

before_script:
  - npm install coffee-script -g
  - npm install forever -g
  - npm install  
  - forever -l ./server.log start -c coffee server.coffee 
  - sleep 1

script:
  - npm test

after_failure:
  - cat ~/.forever/server.log

after_success:
  - echo "done"

notifications:
  slack: ngacn:g7UKlznzOydd9RD1fDwYjXLi
